"""Add voice fields to Organization

Revision ID: 5e021b989657
Revises: 9b8a59754d8f
Create Date: 2026-08-07 09:36:02.760668
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '5e021b989657'
down_revision: Union[str, None] = '9b8a59754d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('voice_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('organizations', sa.Column('voice_phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'voice_phone_number')
    op.drop_column('organizations', 'voice_enabled')
    # ### end Alembic commands ###
