"""Add org hours and location addresses

Revision ID: 9b8a59754d8f
Revises: dadb97cc0ebf
Create Date: 2026-08-07 04:34:36.603842
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '9b8a59754d8f'
down_revision: Union[str, None] = 'dadb97cc0ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('address_line1', sa.String(length=100), nullable=True))
    op.add_column('locations', sa.Column('address_line2', sa.String(length=100), nullable=True))
    op.add_column('locations', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('locations', sa.Column('state', sa.String(length=50), nullable=True))
    op.add_column('locations', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('business_hours', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'business_hours')
    op.drop_column('locations', 'postal_code')
    op.drop_column('locations', 'state')
    op.drop_column('locations', 'city')
    op.drop_column('locations', 'address_line2')
    op.drop_column('locations', 'address_line1')
    # ### end Alembic commands ###
