"""add patient org scope

Revision ID: dadb97cc0ebf
Revises: 20260805_0007
Create Date: 2026-08-07 03:43:27.818402
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'dadb97cc0ebf'
down_revision: Union[str, None] = '20260805_0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('organization_id', sa.Integer(), nullable=True))

    # Backfill with default organization
    op.execute(
        "UPDATE patients SET organization_id = ("
        "SELECT id FROM organizations WHERE slug = 'default-orthopedics'"
        ")"
    )

    op.alter_column('patients', 'organization_id', nullable=False)

    op.drop_index(op.f('ix_patients_email_unique'), table_name='patients')
    op.drop_constraint(op.f('uq_patient_identity'), 'patients', type_='unique')
    op.create_unique_constraint('uq_patient_identity', 'patients', ['organization_id', 'phone', 'date_of_birth'])
    op.create_index('ix_patients_org_email_unique', 'patients', ['organization_id', 'email'], unique=True)
    op.create_foreign_key(op.f('fk_patients_organization_id_organizations'), 'patients', 'organizations', ['organization_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_patients_organization_id_organizations'), 'patients', type_='foreignkey')
    op.drop_index('ix_patients_org_email_unique', table_name='patients')
    op.drop_constraint('uq_patient_identity', 'patients', type_='unique')
    op.create_unique_constraint(op.f('uq_patient_identity'), 'patients', ['phone', 'date_of_birth'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_patients_email_unique'), 'patients', ['email'], unique=True)
    op.drop_column('patients', 'organization_id')
    # ### end Alembic commands ###
